### ISSUE TITLE
Test Database – Hospital Directory

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#10]
Create a small, embedded Java DB database for hospital services and their locations. This is only to prepare you for the first iteration, so the database can have as few as 20 items and a couple fields. Write a program that demonstrates storing and retrieving data using JDBC. When you are finished, create a JAR file that includes the embedded Java DB database.

**Comment by linuxboss182** [comment]
https://www.lucidchart.com/invitations/accept/8a444f5b-38e4-456b-a791-84271ca66d94

Here is the link for the ERD diagram for the database

**Comment by jirassimok** [comment]
I'm adding a bit to the database diagram; but as a separate chart. I won't touch what's already there.
