### ISSUE TITLE
Test Failed DatabaseTester

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#103]
Figure out why this test is failing in `TheRefactor`, is this because we changed the database or is this because we broke something? @jirassimok @ScionIV @WhoEverWroteDatabaseTester

Unzipping /home/travis/.gradle/wrapper/dists/gradle-3.4.1-bin/71zneekfcxxu7l9p7nr2sc65s/gradle-3.4.1-bin.zip to /home/travis/.gradle/wrapper/dists/gradle-3.4.1-bin/71zneekfcxxu7l9p7nr2sc65s
Set executable permissions for: /home/travis/.gradle/wrapper/dists/gradle-3.4.1-bin/71zneekfcxxu7l9p7nr2sc65s/gradle-3.4.1/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)
Download https://repo1.maven.org/maven2/de/dynamicfiles/projects/gradle/plugins/javafx-gradle-plugin/8.8.2/javafx-gradle-plugin-8.8.2.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.1/asm-all-5.1.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-parent/5.1/asm-parent-5.1.pom
Download https://repo1.maven.org/maven2/org/ow2/ow2/1.3/ow2-1.3.pom
Download https://repo1.maven.org/maven2/de/dynamicfiles/projects/gradle/plugins/javafx-gradle-plugin/8.8.2/javafx-gradle-plugin-8.8.2.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.1/asm-all-5.1.jar
Download https://jcenter.bintray.com/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.pom
Download https://jcenter.bintray.com/org/slf4j/slf4j-parent/1.7.21/slf4j-parent-1.7.21.pom
Download https://jcenter.bintray.com/org/apache/derby/derby/10.13.1.1/derby-10.13.1.1.pom
Download https://jcenter.bintray.com/org/apache/derby/derby-project/10.13.1.1/derby-project-10.13.1.1.pom
Download https://jcenter.bintray.com/org/apache/apache/10/apache-10.pom
Download https://jcenter.bintray.com/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar
Download https://jcenter.bintray.com/org/apache/derby/derby/10.13.1.1/derby-10.13.1.1.jar
:compileJava
:processResources
:classes
:jar
:assemble
BUILD SUCCESSFUL
Total time: 33.059 secs
4.82s$ ./gradlew check
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava
Download https://jcenter.bintray.com/junit/junit/4.12/junit-4.12.pom
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
Download https://jcenter.bintray.com/junit/junit/4.12/junit-4.12.jar
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
:processTestResources
:testClasses
:test
DatabaseTester > tester FAILED
    java.lang.AssertionError at DatabaseTester.java:51
31 tests completed, 1 failed
:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/travis/build/linuxboss182/SoftEng-2017/build/reports/tests/test/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 4.375 secs
The command "./gradlew check" exited with 1.
Done. Your build exited with 1.
Top

Search all repositories
 
My Repositories
 
 linuxboss182/SoftEng-2017  246
 Duration: 1 min 7 sec
 Finished: 11 minutes ago

**Comment by jirassimok** [comment]
That's the test for saving the database, which still isn't working quite right. I'll take a look at it tomorrow.

**Comment by ghost** [comment]
Mike and I think we found the issue; he'll be pushing code to fix this soon I think.

**Comment by mteijiro** [comment]
Fixed. The calls to the room constructor needed to be updated to include a node.
