### ISSUE TITLE
Add floors to Database

### ISSUE THREAD

**Issue by jirassimok** [linuxboss182/SoftEng-2017#105]
We want `Nodes` in the database to have a floor (an integer), and the `DatabaseController` needs to retrieve and save that information.

The `Node` class is already ready for this.

**Comment by wggallati** [comment]
Closing issue as a duplicate of Issue #99

**Comment by Jiuchuan9111** [comment]
The Lucid chart is here:https://www.lucidchart.com/documents/edit/495c94c2-dbaa-48bc-9017-18161d549e2b?shared=true&
I added floor entity, later I will change the relations.
