### ISSUE TITLE
statechart diagram 

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#11]
Also an optional statechart diagram if there is interesting state behavior for a single object in your model.

**Comment by linuxboss182** [comment]
Link for statechart diagram:

https://www.lucidchart.com/invitations/accept/d858339a-3eac-4430-b48f-b7fbfb4642b8

**Comment by ghost** [comment]
Will begin work on this issue.

**Comment by mteijiro** [comment]
Should be all set on the state chart diagram. Just need some people to look it over.
