### ISSUE TITLE
Handle multiple floors in UI

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#119]
In the UI we still try drawing lines between nodes across multiple floors.

Instead of trying to draw a line, we should change the color of a node if the next adjacency goes up/down a floor to mark it is an elevator. Later we can make it an elevator icon

**Comment by linuxboss182** [comment]
Additionally we need to finish the "floors traveled through" button

**Comment by TheodoreJBieber** [comment]
On the admin UI, the lines are still drawn between floors, however this is somewhat handy. We will need to talk about this, there's most likely a better way to do it that i can't think of rn
