### ISSUE TITLE
sequence diagram 

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#12]
sequence diagram

**Comment by jirassimok** [comment]
I'm starting to work on this with Joe.

**Comment by linuxboss182** [comment]
Here is the link to the sequence diagram

https://www.lucidchart.com/invitations/accept/ac6c18e9-5795-4a94-8724-9c79b24b083f

**Comment by jirassimok** [comment]
I'm starting work on the sequence diagram.
Just drafting, trying to assemble a general flow to build on.

**Comment by Bobeart** [comment]
I plan on working on this more tomorrow (Monday 3/26) after 6:00 pm. Let me know if that time work for any of you.

**Comment by mteijiro** [comment]
Do you guys need another hand? I'm available tonight at 6 if you're still planning for then.
