### ISSUE TITLE
Database room's need to see their professionals

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#128]
We need this functionality to properly use the tableView

**Comment by ghost** [comment]
I'm fixing the tableview and it shouldn't require any changes to the database.

God help me.

**Comment by linuxboss182** [comment]
@ScionIV I wouldn't waste your time on that - we have a ton of another things to do.

Additionally, we are changing the way all this functionality works. So, you're code probably will not be effective.

**Comment by linuxboss182** [comment]
What we need however, is entities.Room to have an array of entities.Professional, for each that they have.

This change needs to be done when loading the data from the database, nothing needs to be changed when we save them as this informational is already stored. It is loaded so that professionals see their rooms right now, but rooms cannot see their professionals. 

I highly discourage you from touching the tableview. It's 2 minutes of work once the database loads properly, and me and @TheodoreJBieber have an idea of how to make the UI work already. We already have an idea of how to do it and half the code for it, the issue was for the database only. Don't waste time trying to figure out how the time listeners work, especially if you not pair programming with either me or @TheodoreJBieber.

**Comment by linuxboss182** [comment]
@ScionIV finished this, closing
