### ISSUE TITLE
class diagrams 

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#13]
Provide class diagrams with attributes, methods, associations, and inheritance for your controllers, entities and boundaries. Since this is the analysis phase, you may use rough descriptions of data types.

**Comment by linuxboss182** [comment]
Additionally: Create the detailed class diagram for your minimal application. Specify the actual data types you plan to implement, the methods and their signatures. You do not need to create a detailed sequence diagram. However, if you decide to do so, include it in this section.

**Comment by linuxboss182** [comment]
Working on this 5-7 on Saturday

**Comment by linuxboss182** [comment]
Class diagram for minimal application has been completed. 

https://www.lucidchart.com/invitations/accept/ad9523cc-bc21-4d55-921d-7cd5be98ff0a

**Comment by jirassimok** [comment]
That's still missing a few things, I think. I've got some other work to do now, but I can spare some time to finish it up tomorrow.

**Comment by jirassimok** [comment]
I'm working on some of the class diagram in the Octowedge. (Mostly just reasoning out details that we haven't added yet.)

(I'm adding things in red, except essential things that weren't already present (like the `Building` class, and its relation to `Floor`).

**Comment by jirassimok** [comment]
Here's a copy for just the minimal application.

~https://www.lucidchart.com/invitations/accept/9a8210e5-e236-489b-a392-7d3e17646d36~

Never mind that; we can just extract it from the general diagram when we need it.
