### ISSUE TITLE
Symbols for bathrooms, elevators, etc.

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#132]
We need a way to identify these, we can make .getShape return the imageview for the icon.

Shouldn't be too hard because it only affects code inside .makeShape, and changes nothing else.

**Comment by jirassimok** [comment]
No, changing shape also changes anywhere we change the color of the symbols on the map.

(This is why I want to push actual color-changing out of the Controllers.)

**Comment by linuxboss182** [comment]
just make color changing a method a node, shouldn't take more than 20 minutes to do

**Comment by jirassimok** [comment]
I could do it poorly in 20 minutes, but to make it safe to work with and easily extensible requires more effort, and more importantly, careful consideration of our design patterns and abstractions.

**Comment by linuxboss182** [comment]
javafx.Node shape;

```java
public void setColor(Color aColor){
   if(this.shape instanceOf(Shape){
     shape.setColor(aColor)
   }
}
```

We store javafx.Node inside entities.Node instead of having java.fx circle, we check to make sure shape is a shape before we call set color.

done. ?

**Comment by linuxboss182** [comment]
Let's just do it poorly and fix it later, agile design ftw

**Comment by jirassimok** [comment]
That's... not how agile works.

Any use of `instanceof` is a sign of poor design; we want our design to be good.

In any case, I might have a partial way around it, but I'll need some help from Stove or Ted.

**Comment by linuxboss182** [comment]
Edit: Let's do the above in room, leave node how it stands. 

Edit 2: we need to change makeShape also, 

if we stored the location string to the .png in the database we could make it work

```java
String pngLocation;
public void makeShape(){
if(pngLocation != null){
shape = new imageView(pngLocation...)
}
else{
new Rectangle()
}
}
```

**Comment by linuxboss182** [comment]
There is definitely cases where instanceof is acceptable, this might be one.

But, another idea:

we already have a stackpane, we could draw the circle/rectangles exactly like we are and make the imageView for icons just display to the left on the stackpane.

**Comment by jirassimok** [comment]
Yeah, that's basically what my workaround is.

No; this is not a case for `instanceof`, this is a case for better design. I know because I have ideas about what the better design is.

**Comment by linuxboss182** [comment]
@jirassimok are you doing this during this iteration? If you plan on doing it this iteration, make this a priority. Else skip it.
