### ISSUE TITLE
Fix failing multi-floor test case 

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#142]
One of the tests are failing

**Comment by wggallati** [comment]
Fun fact - the test passes in dev/master, but fails in origin/master. Looks like the problem isn't with the test but with the disparity between branches

**Comment by jirassimok** [comment]
Oh; yeah. Forgot there was an issue for this. The problem was a change I made in Node that prevented connecting roomless nodes across floors.

That should be fixed now.
