### ISSUE TITLE
Handle nonexistent paths

### ISSUE THREAD

**Issue by jirassimok** [linuxboss182/SoftEng-2017#146]
Right now, if you try to find a path between rooms with no connection, an error occurs.

I've added a TODO to `UserPathController` in `dev/algorithms`.

**Comment by mteijiro** [comment]
There is now an alert box that will pop up when this happens. Still need to find a way to close the pathfinding screen when this occurs.

**Comment by linuxboss182** [comment]
Making separate issue "Still need to find a way to close the pathfinding screen when this occurs."
