### ISSUE TITLE
Allow rooms without Nodes

### ISSUE THREAD

**Issue by jirassimok** [linuxboss182/SoftEng-2017#149]
This allows rooms to be read from a file as well as professionals, and potentially allows other nice things like switching which node represents a room.

**Comment by jirassimok** [comment]
I'm making a change so rooms without nodes won't display to users.

I'll need someone else to figure out how the admin UI needs to change to accommodate this one.

**Comment by jirassimok** [comment]
That's done.

It was in commit 557e22d0ee33ae56de62347c89acdd977b7c6801, where I forgot to mention it.

**Comment by linuxboss182** [comment]
Closing issue because you said it's done
