### ISSUE TITLE
EditorController algorithm switching 

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#168]
Set the onChange listener for the dropdown in editorController to select an algorithm

**Comment by jirassimok** [comment]
That should already be working.

**Comment by jirassimok** [comment]
We need the box to be a ChoiceBox, not a ComboBox; I don't know how to fix that in Scene Builder.

Besides that, I have a commit ready to fix this.

**Comment by linuxboss182** [comment]
Got it, I'll switch it now

**Comment by linuxboss182** [comment]
What branch is this working on ? I'll just change it on dev/master and you can pull the change

**Comment by jirassimok** [comment]
It's on `dev/master`.

**Comment by linuxboss182** [comment]
Done! Somebody needs to test it now

**Comment by jirassimok** [comment]
On it.

**Comment by jirassimok** [comment]
It's working.
