### ISSUE TITLE
Add "set kiosk" to admin UI

### ISSUE THREAD

**Issue by jirassimok** [linuxboss182/SoftEng-2017#171]
This button should be in the room editing controls, and probably should read "set location of this kiosk".

**Comment by stevenmcateer** [comment]
So would the button click set the selected node as the kiosk? essentially just update its name to "you are here"

**Comment by jirassimok** [comment]
Like that, but without the name change; we've got the Kiosk in the DB and Directory now.

(Oops; wrong button.)

**Comment by linuxboss182** [comment]
Rather, updating the directory we handle it properly now in the DB

**Comment by jirassimok** [comment]
There should be a comment at the bottom of EditorController describing how to do it.

**Comment by linuxboss182** [comment]
Directory.setKiosk(Node), or equivalent

**Comment by stevenmcateer** [comment]
So the button will just do Directory.setKiosk(Node), with Node being the selected node on the map?

**Comment by linuxboss182** [comment]
Yes
