### ISSUE TITLE
If a path visits the same floor twice, the exit and entry points should not connect.

### ISSUE THREAD

**Issue by jirassimok** [linuxboss182/SoftEng-2017#177]
e.g. If a path goes up an elevator, down a hall, then down an elevator, the elevators on the first floor will be connected when the path is drawn. This is not what should happen.

This probably requires a fix somewhere in UserPathController.

**Comment by jirassimok** [comment]
To solve this, UserPathController should draw the path in segments, rather than connecting all nodes on the floor in sequence.

**Comment by Bobeart** [comment]
Should be fixed now, Path is now segmented, and only displays / paints the path on the floors in the order that it shows up on the floor.
