### ISSUE TITLE
Refactor a whole lot of stuff.

### ISSUE THREAD

**Issue by jirassimok** [linuxboss182/SoftEng-2017#192]
See Refactoring Plans and Iteration 4 Improvement plans on the wiki.

Don't change stuff right now.

**Comment by ghost** [comment]
👌 💯

**Comment by jirassimok** [comment]
New and exciting additions:

UserPathController shouldn't inherit from UserMasterController.

**Comment by jirassimok** [comment]
The biggest refactors are done.
