### ISSUE TITLE
Fix text directions

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#203]
Text directions should be tested&revised.

They do not look good traveling long distances or between buildings.

Additionally, we might want to consider putting icons along with the text.

**Comment by linuxboss182** [comment]
The following functionality will look like this:

switch(node.getType()){
case ELEVATOR:
break;
case BATHROOM;
break;
default:
}

**Comment by jirassimok** [comment]
Existing work on branch `dev/getDirections`

**Comment by Bobeart** [comment]
Text Directions now work and can be easily formatted into strings with icons attached now
