### ISSUE TITLE
Re-write icons/rooms

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#209]
Nodes should contains a circle.

Rooms should be gutted (remove icons, shapes, one constructor, etc.)
 - should contain a single entity.icon, which holds label and imageview 

Icons should be an entity, 
 - contains a enum for type to a resources\image 
 - contains an imageview 
 - contains a label

**Comment by mteijiro** [comment]
Icon functionality is in. All that is left is to make an easy way for the admin to set room types. And create actual icon images for when a room is selected as origin or destination (currently we cycle through placeholders),
