### ISSUE TITLE
Convert autocad files

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#210]
a. Add the ability to have hospital employees perform pathfinding to Faulkner main hospital locations (at the suite level, except for the 7th floor) on the Autocad diagrams. Obviously, you will need to convert the remaining floors of Faulkner except for floor 7 (because of the large number of locations). An optional feature would be to include employee locations in Belkin House and the 7th floor of Faulkner. Permit employees the ability to enter Suite locations or numbers to specify their destinations. Hospital visitors should still be able to do pathfinding restricted to the locations on the previous maps.

**Comment by ItsJackEMoore** [comment]
Finished the DWGs that refused to work with autoCAD, vector mapping should still be in the PNGS due to adobe illustrator.
