### ISSUE TITLE
Cover Sheet

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#215]
a cover sheet with Worcester Polytechnic Institute, Computer Science Department, CS3733-01-D17, Prof. Wilson Wong, name of your team, names of members and their positions, and the name of your team coach. If members switched positions, mention which positions for which iterations.

**Comment by ItsJackEMoore** [comment]
This should be done, It is under iteration 4 in Presentation & Turn ins in Team Document and Deliverables
