### ISSUE TITLE
Make rooms not disappear when clicked in paths

### ISSUE THREAD

**Issue by jirassimok** [linuxboss182/SoftEng-2017#219]
After finding a path, clicking a room (just the circle) causes all rooms to disappear.

As a temporary fix, I have added a listener so all nodes will redraw after clicking on the pane.

When the rooms are clicked, the listeners added in UserMasterController are called, which causes the shapes to be reset.

I believe the simplest solution may be to add an additional pane on top of the nodePane in UserPathController, and use it to prevent clicking on rooms. The challenge is to do so while still allowing map manipulation.

A more comprehensive solution could be created as part of the room Icon system.

**Comment by wggallati** [comment]
Issue closed, could not reproduce
