### ISSUE TITLE
Entity Classes

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#22]
We need our detailed class diagram to be translated into several class files with blank code

We should make our folder structure so that entities and controllers are in their own packages

A package called "entities" and another called "controllers" with UI in their own folder, and database files in its own folder

**Comment by jirassimok** [comment]
I'll be starting the Node class tomorrow (or maybe tonight).
I'll be free all day after class.

**Comment by linuxboss182** [comment]
Be sure to post your available times to meet with people to pair program the issues

**Comment by jirassimok** [comment]
I've been working on node in the branch `base/node`.

**Comment by TheodoreJBieber** [comment]
I worked on the branch creatingEntities, I'll submit a pull request to merge that branch and base/node

**Comment by linuxboss182** [comment]
Awesome job @TheodoreJBieber  I love the code its beautiful
