### ISSUE TITLE
Use Stage::setScene instead of Scene::setRoot to switch between the major controllers

### ISSUE THREAD

**Issue by jirassimok** [linuxboss182/SoftEng-2017#222]
I'm fairly certain that changing scene a more correct approach than changing which FXML the current scene contains for when we change to other parts of the application. The login window and about page are small enough that the current method might make sense, but to switch between the Editor and User controllers, we really are changing which part of the application is being displayed.

I've added `Application::getStage` to allow use of the refactored `UserPathController`, but I have not set it up anywhere else.

If you want to try handling this, look where there are scene switches, and change them to use `Stage::setScene` instead of getting the scene from the current controller and switching "scene" with `Scene::setRoot`.

The only current use of setStage in the project is in `UserMasterController::getDirectionsClicked`, but this use also uses other techniques (to set up the path controller). If you refer to this function, only pay significant attention to the lines that use `ApplicationController::getStage`.

**Comment by linuxboss182** [comment]
This will be done with memento pattern so I'm closing this
