### ISSUE TITLE
A* algorithm

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#23]
We need the main, core code for A* written. 

This is probably going to need several people to accomplish this!

**Comment by jirassimok** [comment]
The algorithm itself won't be that hard.

The modifications it needs to work with everything else could be tricky.

I suggest that whoever is working on this talk to people who have a clear understanding of how the application fits together.

**Comment by linuxboss182** [comment]
This is for only the algorithm, we need a group of people to fully understand how A* works and implement the algorithm for it

**Comment by jirassimok** [comment]
We've started work on the `Pathfinder` class and A* algorithm.

**Comment by jirassimok** [comment]
Currently implementng

**Comment by jirassimok** [comment]
Implemented and merged to master; needs some test cases.
