### ISSUE TITLE
Floor Thumbnails Building

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#234]
The professor said one of the things he hated most about our path viewer was there was no way to tell which "floor 1" belonged to which building. 

We should edit the thumbnails to include something for the building, or group and label them by building.

**Comment by linuxboss182** [comment]
I'm thinking we put a label below each thumbnail that says something like "Faulkner 1", it shouldn't be hard because we already have the strings "Faulkner" and "Belkin" as fields stored in the DB, we would just do floor.buildingname+floor.getNumber() and make a dynamic label attached a few pixels under the thumbnail. I'll work on this during the evening because I don't think it will take me long.

**Comment by ghost** [comment]
Looking into this

**Comment by ghost** [comment]
Changes added to dev/master. Label Y value needs adjustment; I can't see the bottom of the image with my current environment.
