### ISSUE TITLE
Handle different floors for professionals/visitors 

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#240]
I'm going to focus on handling different floors dependent on permission level

**Comment by TheodoreJBieber** [comment]
The way I have thought about this is by having certain nodes require privileges to travel to.

**Comment by wggallati** [comment]
Made branch dev/professionalNodes, needs UI implementation

**Comment by linuxboss182** [comment]
I finished this by adding a view restricted toggle
