### ISSUE TITLE
Excel Room editor

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#241]
Upon Wong recommendation we should;

Import rooms from CSV, make X and Y show up at cursor location to be able to add to spreadsheet

**Comment by TheodoreJBieber** [comment]
Floor and building numbers are necessary also for the csv probablllllly

**Comment by ghost** [comment]
Will look into this

**Comment by ghost** [comment]
Button's in a weird location but this is pretty much done on dev/master
