### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#25]
We should have a basic set of JUnit tests for iteration 1

We also need Gradle and TravisCI setup

Group will work directly with test engineer

**Comment by linuxboss182** [comment]
We need test cases for 

1. Textual Directions
2. Path finding 
3. Database read/write

**Comment by mteijiro** [comment]
I'm gonna create a google doc for us to list what still needs to be tested. For organizational purposes. 
https://docs.google.com/document/d/1YoEDTK9R7O9ZuPggD49Ds1TYrLlQk8uxPHb2bjWIz4E/edit#

**Comment by linuxboss182** [comment]
Also, another big part of this will be for trying test cases against the UI objects themselves. 

You'll have to read-up about how to test JavaFX with JUnit, but there should be a way to simulate hitting buttons on the UI. 

Like, you would write a test case that simulates opening the application, hitting the button that selects a location and a destination, and ensure that it gets you the right path object.
