### ISSUE TITLE
Minor bugs with new UI

### ISSUE THREAD

**Issue by stevenmcateer** [linuxboss182/SoftEng-2017#256]
- ~Panning on path screen broke for some reason, should be an easy fix with .pickOnBounds(false) but not sure.~
- ~Typing in the destination field sometimes throws errors but still sets the dest~

**Comment by linuxboss182** [comment]
Additionally, the "You are here" box doesn't clear on focus

**Comment by linuxboss182** [comment]
And, when I focus on the start box my listview doesn't populate until I start searching

**Comment by linuxboss182** [comment]
Can't pan, can't zoom, the text for directions is like.... blurred?

[7:40] 
The zoom slider doesn't work

[7:40] 
The white buttons at least to me don't really stand out? Maybe gray (lower priority)

[7:40] 
And it's the screen we want to look the best

[7:41] 
Oh also, A and B on the path displaying area are offset from eachother (the text is fucked)

[7:41] 
And Walt had a really good idea where we draw A and B symbols on the map for start and end which would be super cool, too

**Comment by linuxboss182** [comment]
We should also make enter select the next box for the start/end selection

**Comment by linuxboss182** [comment]
+ re-enable keyboard shortcuts (example zoom, etc)

**Comment by linuxboss182** [comment]
When we hit any popup twice (SMS, Help, about, etc, etc), we get two windows. 

If you rapidly hit the button you can get a hundred of those windows (we shouldn't load up one if one is already open)

**Comment by linuxboss182** [comment]
User help button pop-up needs a button

**Comment by linuxboss182** [comment]
Professional rooms aren't colored in editorController

**Comment by linuxboss182** [comment]
Change text directions into a scrollable box so it doesn't overflow

**Comment by wggallati** [comment]
~- Professional nodes show up in directory even when professional is not logged in~
- ~Logging in as admin right after logging in as professional starts admin editing professional mode despite toggle in Pathfinder tab saying editing in user~
- When not editing in professional mode, professional nodes are still visible, ~but cannot make connections between each other. Professional to public node connections and vice versa work but connections between professional nodes can only be done in professional mode~

**Comment by Waltor23** [comment]
Cancel button does not work in Add Professional popup
