### ISSUE TITLE
Labels in editorController 

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#258]
We need to fix the font size for labels, they are too small. 

Lower priority but; (copied from previous issue)
When you pan or zoom in the editor, and try to move labels, it does not work as you would expect. Give it a try and you'll see. Basically, if we don't fix this before the presentation, we want to disable/reset the zooming and panning when we edit the labels. Low priority, but is quality of life change and if it is not addressed we cannot show it in the presentation.

**Comment by jirassimok** [comment]
Fixed
