### ISSUE TITLE
Node.distanceTo(Node)

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#26]
We need the method .distanceTo written.

The method will take in a node as a argument, and be a method in the class node. 

Basically, this function is the distance formula.

**Comment by jirassimok** [comment]
I've got this; it's already in javafx.util.Point2D, which I'll probably be using in Node.

This is small enough that it probably doesn't warrant an issue of its own.

**Comment by linuxboss182** [comment]
I understand that you could do this easily, but as the professor said in lecture this isn't the design of the class.

He specifically said to create smaller issues for the junior developers.

Be sure to work with others in groups of at least 2, doing real pair programming (on one computer) to solve any issues.

**Comment by jirassimok** [comment]
Small issues, yes. But I think this qualifies as even more trivial than that. It's _actually_ just a well-known equation.

I'll be doing the core of the Node class (as an exercise to refamiliarize myself with Java), but I'll leave most of the methods empty.

**Comment by wggallati** [comment]
Assigned myself to this because it's integral to the A* algorithm which I am also writing. It would probably be good if somebody else signed up for both so we can knock both out in one sitting

**Comment by jirassimok** [comment]
I'm in.

Also, turns out `javafx.Point2D` uses `double`, so we'll want to reimplement it anyway.
