### ISSUE TITLE
Directions generator breaks with straight turns at the start or end of the path

### ISSUE THREAD

**Issue by TheodoreJBieber** [linuxboss182/SoftEng-2017#261]
Robert should be on this issue because he wrote the new text directions. 
The issue is because of an index out of bounds, specifically with straight turns.
Create a path that starts with a straight, then the rest doesn't matter, then end it with a straight.
Then get directions from that start to the end

**Comment by jirassimok** [comment]
This line is throwing an IndexOutOfBounds exception in some cases; I assume it's part of the same problem.

`turnAngle = path.get(i).angle(path.get(i + 1), path.get(i - 1));`

**Comment by TheodoreJBieber** [comment]
Indeed it is

**Comment by ghost** [comment]
I made it not do this. It shouldn't error out anymore.
