### ISSUE TITLE
Node.isLeftTurn(Node, Node)

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#27]
This function takes in two nodes, so it will operate on three nodes.

The purpose of this function is to tell if a turn is a left or right, but to do so it needs to calculate the angle between three nodes. 

Should return a boolean indicating if the turn is a left.

**Comment by Jiuchuan9111** [comment]
I will start to work on this.

**Comment by Jiuchuan9111** [comment]
I will help doing this.

**Comment by jirassimok** [comment]
I recommend returning an angle instead. Left/right might not be enough information (not all turn will be exactly 90 degrees).
