### ISSUE TITLE
Can create an elevator to two different elevators on the same floor, but are prevented from logging out as a result of doing such

### ISSUE THREAD

**Issue by wggallati** [linuxboss182/SoftEng-2017#276]
It makes sense to not allow them to log out, but a popup notification that they goofed might be more helpful

**Comment by jirassimok** [comment]
Wait, what?

**Comment by wggallati** [comment]
If you create two rooms on the same floor, and connect an elevator to both of them, it lets you. It doesn't let you log out though until you figure out you connected one elevator to two different elevators on the same floor. This wouldn't be a problem if it a) prompted you or b) had some indicator as to where the elevator is connected to, but it could be confusing after a long night of editing

**Comment by jirassimok** [comment]
This is a non-issue.

Connections between floors may not be elevators. Stairs, for example, may connect floors in multiple directions.
