### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#3]
Somebody should write-up some things in the readme file, its looking lacking.

**Comment by jirassimok** [comment]
We don't have anything to put in it yet.

**Comment by linuxboss182** [comment]
Could just write up a general of what the project is. 

From Part B;

Project Introduction
Your team will create a prototype pathfinding kiosk application for patients and visitors at the Faulkner Hospital. There will be kiosks throughout the hospital. Users can select from a list of doctors or departments to visit and the application will display and print the path to their destinations. The application consists of two equally important components – the user pathfinding application and the admin tool to manage maps, paths, and doctor/department directories. The various versions of the floor plans and annotated floor plans have been provided. A directory of the doctors and departments per floor have also been included. The project is divided into the following:

**Comment by jirassimok** [comment]
I suggest we move to Trello.

Also, this sounds like a job for our Documentation Analyst.

**Comment by wggallati** [comment]
I'll discuss the Trello-GitHub split at scrum tomorrow, we'll decide on one by the end of our meeting Saturday.

**Comment by linuxboss182** [comment]
Test of github-slack bot

**Comment by linuxboss182** [comment]
Let's put the screen shots and the descriptions from project C into the readme.md and make it look nicer, the professor is coming! haha.
