### ISSUE TITLE
Rooms contain Nodes

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#72]
We need to refactor the code to make rooms contain nodes instead of inheriting from them

branch name `refactoring\Directory`

**Comment by linuxboss182** [comment]
@jirassimok  will lead this

**Comment by mteijiro** [comment]
Jacob and I are working on combining the Room and Node class right now

**Comment by mteijiro** [comment]
We're going to be working on the refactor/node branch.
Working on fixing a bunch of refactoring errors before applying changes to master.

**Comment by jirassimok** [comment]
The base issue is complete, but the rest of the program does not work around this yet.
