### ISSUE TITLE
Create separate panes for different layers

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#77]
This is specifically putting circles on one pane, and lines on another.

Additionally change effected code, specifically remove the ArrayList for circles/rectangles and update redrawing to use .getChildren().removeAll

Possibly make methods for .removeAll in map controller as well 

@TheodoreJBieber will lead this

branch names `refactoring\UI`

**Comment by stevenmcateer** [comment]
Sign me up....................boi
