### ISSUE TITLE
6th Floor Autocad

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#79]
This has no attached milestone, but must be done for this iteration. 

Whoever is interested in it must be capable of learning autocad within a week, so prior CAD experience will be incredibly helpful whether its solid works or whatever.

**Comment by Jiuchuan9111** [comment]
I'll try to search for some information about this first.

**Comment by linuxboss182** [comment]
Did you guys finish this?

**Comment by Bobeart** [comment]
I have some friends who kind of know how to use autocad so I could ask them for advice on how to do this

**Comment by ItsJackEMoore** [comment]
The dwg that professor Wong gave us is from an autocad from 2 years ago. I use emodeler to get the closer thing that I could get. It is in the google drive under iteration 2.
