### ISSUE TITLE
Research resizing/zooming the map

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#81]
Do some research and determine if we should or should not implement this during this iteration. 

@me will lead

**Comment by TheodoreJBieber** [comment]
I have a general idea of how this could work.
Basically, 
keep track of the original size of the map
keep track of the current size of the map
and keep track of the map offset (assuming you can drag around on the map to move it)

any position to be drawn on the map should be drawn at: [X*((current size)/(original size)) + xOffset, same idea for Y]

**Comment by ItsJackEMoore** [comment]
I am interested in helping on this topic
