### ISSUE TITLE
Determine shortcut icons

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#83]
Review surveys, interviews, etc about which short cuts we should have, and what icons would be appropriate to add. 

@me will lead

**Comment by ItsJackEMoore** [comment]
Are we speaking icons through CSS changing assets to pngs or just via code? either way I am interested in this topic

**Comment by linuxboss182** [comment]
Like on the map we would have bathroom icons for bathrooms, etc. In addition other icons for finding nearest bathroom

**Comment by Bobeart** [comment]
Get left turn, right turn icons

**Comment by Jiuchuan9111** [comment]
All done. Including icons for turnings and start/end.
