### ISSUE TITLE
Reading from some sort of tabular data file

### ISSUE THREAD

**Issue by TheodoreJBieber** [linuxboss182/SoftEng-2017#85]
This issue would consist of programming something that lets our program read from the excel files provided on the MyWPI website. They could potentially be added into memory, and an admin could go in and accept them into the database.
This probably won't be extremely easy, but it could be a good innovative feature for iteration 2.

**Comment by jirassimok** [comment]
I'm doing this now.

**Comment by jirassimok** [comment]
This is done.

We still need a few buttons for it, but that's another issue.
