### ISSUE TITLE
Database controller cleanup

### ISSUE THREAD

**Issue by ghost** [linuxboss182/SoftEng-2017#86]
Hardcoding of tables/columns in the database controller and stored procedures class needs to be remedied. Also, there are functions not in use(developed before we decided to just populate the directory) and blocks of code that are commented out that need to be evaluated/removed.

**Comment by linuxboss182** [comment]
use StoredProcedures for this

**Comment by jirassimok** [comment]
It's actually called [`PreparedStatement`](https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html).

It would be great to have an API that allows us to change one or two strings total for any change to the data structures.

**Comment by jirassimok** [comment]
I'm adding height values to the database.

**Comment by linuxboss182** [comment]
Are we using prepared statements now ?
