### ISSUE TITLE
Functional Model

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#9]
"Summarize the results from your surveys and interviews. Include the raw data as Excel (survey) and Word (interviews) attachments."
We have this mostly done, just finalize the document and put it all together.

"With additional guidance from your survey results and interviews, determine as best as possible the application features that your team would like to implement by the end of the term."
We will re-finalize this during meeting on Sunday?

" Create user stories and determine their sizes for all of these features. This list of prioritized user stories will comprise the product backlog that your product owner will manage. You will NOT create use cases for all of them at this point. Instead create use cases just for your minimal application. These application features and corresponding user stories are not necessarily fixed for the entire term but may be modified as you work through your later iteration"
We should strip down our use cases to minimal application for submission of part c

**Comment by Bobeart** [comment]
All survey data has been put in excel, Still waiting on interview responses
