### ISSUE TITLE
Update diagrams with new refactoring 

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#96]
Ask any lead about changes done with refactoring to update diagrams

**Comment by linuxboss182** [comment]
Who was working on this? @Bobeart @mteijiro and who else?

**Comment by mteijiro** [comment]
I think @ItsJackEMoore should also be on this as documentation analyst. A lead or assistant lead engineer would be helpful as well to clarify how all of our systems work.
