### ISSUE TITLE
A* Multiple floors

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#98]
Updating pathfinder to handle multiple floors

**Comment by jirassimok** [comment]
This should mostly entail making sure that once you change floor, you are only allowed to continue on the same floor as the destination (each path should only change floor once).

**Comment by mteijiro** [comment]
Gonna see if I can fix this. Wrote a test for this to check if it works.

**Comment by wggallati** [comment]
Fixed it with a change to the distanceTo function in Node that poisons floor connection weights such that it will only send you up and back down an elevator if it is faster than walking the entire time you're waiting for the elevator. Timing was based on SL's slow-ass elevator so we should be fine with regards to effectiveness.
